#!/bin/sh

ln_args=''
while getopts 'f' o; do
	case $o in
	f) ln_args="$ln_args -f";;
	*) exit 1;;
	esac
done

shift $((OPTIND-1))

if [ $# -ne 2 ]; then
	>&2 echo "usage: mkdynlink <contents> <target>"
	exit 1
fi

case $1 in
*/*)
	>&2 echo "error: / must be replaced with %S"
	exit 1
	;;
esac

ln $ln_args -sv -- /mnt/dynlinkfs/"$1" "$2"
